{
 "title": "VW GC600",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Actual Position",
   "type": "geomap",
   "description": "VW Grand California GPS Position",
   "gridPos": { "h": 29, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"WeJson\"] == \"weconnect/rawjson\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_parking_parkingPosition_latitude\" or r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_parking_parkingPosition_longitude\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"host\", \"WeJson\"])\n  |> rename(columns: {vehicles_WV1ZZZSYZM9019663_domains_parking_parkingPosition_latitude: \"lat\", vehicles_WV1ZZZSYZM9019663_domains_parking_parkingPosition_longitude: \"lon\"})\n  "
    }
   ]
  },
  {
   "title": "Car Status",
   "type": "canvas",
   "description": "Overall Status",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"WeJson\"] == \"weconnect/rawjson\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_access_accessStatus_overallStatus\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Door Locked",
   "type": "canvas",
   "description": "Door Lock Status",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"WeJson\"] == \"weconnect/rawjson\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_access_accessStatus_doorLockStatus\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "AD Blue Range",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"WeJson\"] == \"weconnect/rawjson\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_measurements_rangeStatus_adBlueRange\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Lights Status",
   "type": "canvas",
   "description": "Door Lock Status",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"WeJson\"] == \"weconnect/rawjson\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_vehicleLights_lightsStatus_lights_left_status\" or r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_vehicleLights_lightsStatus_lights_right_status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Fuel Level",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"WeJson\"] == \"weconnect/rawjson\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_measurements_fuelLevelStatus_currentFuelLevel_pct\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Windows Status",
   "type": "canvas",
   "description": "Windows Status",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"WeJson\"] == \"weconnect/rawjson\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_access_accessStatus_windows_frontLeft_openState\" or r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_access_accessStatus_windows_frontRight_openState\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Door Open Status",
   "type": "canvas",
   "description": "Door Status",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"WeJson\"] == \"weconnect/rawjson\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_access_accessStatus_doors_frontLeft_openState\" or r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_access_accessStatus_doors_frontRight_openState\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Fuel Range",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"WeJson\"] == \"weconnect/rawjson\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_measurements_rangeStatus_dieselRange\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Inspection Service KM",
   "type": "bargauge",
   "description": "How many KM before next Service",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_vehicleHealthInspection_maintenanceStatus_inspectionDue_km\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Inspection Service Days",
   "type": "bargauge",
   "description": "How many DAYS before next Service",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_vehicleHealthInspection_maintenanceStatus_inspectionDue_days\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ODO Meter",
   "type": "canvas",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "KM" } },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_vehicleHealthInspection_maintenanceStatus_inspectionDue_days\" or r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_vehicleHealthInspection_maintenanceStatus_inspectionDue_km\" or r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_measurements_odometerStatus_odometer\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Oil Service KM",
   "type": "bargauge",
   "description": "How many KM before next OIL Service",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_vehicleHealthInspection_maintenanceStatus_oilServiceDue_km\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Avg Consuption",
   "type": "canvas",
   "description": "Average Consuption l/100km",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "l/100km" } },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"WeJson\"] == \"weconnect/rawjson\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_trips_cyclic_averageFuelConsumption\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Oil Service Days",
   "type": "bargauge",
   "description": "How many DAYS before next Oil Service",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Master\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"WeConnect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vehicles_WV1ZZZSYZM9019663_domains_vehicleHealthInspection_maintenanceStatus_oilServiceDue_days\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}